apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: una
  labels:
    app: una
spec:
  replicas: 1
  selector:
    matchLabels:
      app: una
  template:
    metadata:
      labels:
        app: una
    spec:
      containers:
        - image: una
          name: una
          env:
          - name: UNA_DB_HOST
            value: mysql:3306
          - name: UNA_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
          ports:
            - containerPort: 80
              name: una
          volumeMounts:
            - name: una-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: una-persistent-storage
          gcePersistentDisk:
            pdName: una-disk
            fsType: xfs
