apiVersion: v1beta1
id: mysql
desiredState:
  manifest:
    version: v1beta1
    id: mysql
    containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
           # change this
            value: password
        cpu: 100
        ports:
          - containerPort: 3306
        volumeMounts:
            # name must match the volume name below
          - name: mysql-persistent-storage
            # mount path within the container
            mountPath: /var/lib/mysql
    volumes:
      - name: mysql-persistent-storage
        source:
          persistentDisk:
            # This GCE PD must already exist and be formatted xfs
            pdName: mysql-disk
            fsType: xfs
labels:
  name: mysql
kind: Pod